spring:
  application:
    name: feature-management-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/feature_management}
    username: ${SPRING_DATASOURCE_USERNAME:fms}
    password: ${SPRING_DATASOURCE_PASSWORD:fms}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

server:
  port: ${SERVER_PORT:8080}
