apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db"
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  url: {{ required "app.datasource.url is required" .Values.app.datasource.url | quote }}
  username: {{ required "app.datasource.username is required" .Values.app.datasource.username | quote }}
  password: {{ required "app.datasource.password is required" .Values.app.datasource.password | quote }}
